---

- name: install ambari-agent
  yum: name=ambari-agent state=latest

- name: Configure ambari-server hostname in ambari-agent configuration
  lineinfile: dest=/etc/ambari-agent/conf/ambari-agent.ini regexp=^.*hostname=.*$ line=hostname={{ item }} backup=yes
  with_items:
    - "{{  hostvars[groups['ambari'][0]]['ansible_nodename']  }}"

- name: Ensure ambari-agent is running and enabled
  service: name=ambari-agent state=started enabled=yes

- name : wait for agent to register
  command : sleep 10
