
---

    
- name: Install Ambari repo.
  get_url: url="{{ ambari_repo_url }}" dest=/etc/yum.repos.d/ambari.repo
- name: Install HDP repo.
  get_url: url="{{ hdp_repo_url }}" dest=/etc/yum.repos.d/hdp.repo

- name: Install HDP util repo.
  get_url: url="{{ hdp_util_repo_url }}" dest=/etc/yum.repos.d/hdp_util.repo
  
- name: Import Ambari Repo GPG key.
  rpm_key:
    key: "{{ ambari_repo_gpg_key_url }}"
    state: present
    
    
- name: install createrepo
  yum: name={{ item }} state=latest
  with_items:
   - createrepo
   - yum-utils
  
- name: Install nginx
  yum: name={{ item }} state=present
  with_items:
   - nginx

- name: nginx service state
  service: name=nginx state=started enabled=yes
 
- name : Create ambari local repo directory
  file : dest=/usr/share/nginx/html/ambari/centos{{ ansible_distribution_major_version }}/Updates-ambari-2.2.0.0 state=directory mode=0755

- name: reposync with remote ambari repo
  command: "{{ item }} chdir=/usr/share/nginx/html/ambari/centos{{ ansible_distribution_major_version }}/"
  with_items:
   - reposync -r Updates-ambari-2.2.0.0 
   - createrepo /usr/share/nginx/html/ambari/centos{{ ansible_distribution_major_version }}/Updates-ambari-2.2.0.0

- name : Create HDP local repo directory
  file : dest=/usr/share/nginx/html/hdp/centos{{ ansible_distribution_major_version }}/HDP-2.3.4.0   state=directory mode=0755
  
- name: reposync with remote hdp repo
  command: "{{ item }} chdir=/usr/share/nginx/html/hdp/centos{{ ansible_distribution_major_version }}/"
  with_items:
    - reposync -r HDP-2.3.4.0 
    - createrepo /usr/share/nginx/html/hdp/centos{{ ansible_distribution_major_version }}/HDP-2.3.4.0

- name : Create HDP util local repo directory
  file : dest=/usr/share/nginx/html/hdp_utils/centos{{ ansible_distribution_major_version }}//HDP-UTILS-1.1.0.20 state=directory mode=0755
  
- name: reposync with remote hdp-util repo
  command: "{{ item }} chdir=/usr/share/nginx/html/hdp_utils/centos{{ ansible_distribution_major_version }}/"
  with_items: 
   - reposync -r HDP-UTILS-1.1.0.20 
   - createrepo /usr/share/nginx/html/hdp_utils/centos{{ ansible_distribution_major_version }}/HDP-UTILS-1.1.0.20